### ISSUE TITLE
[建议]未包含换行符的LRC格式兼容

### ISSUE THREAD

**Issue by u3u** [MoePlayer/APlayer#110]
如果压缩了换行符 `\n` 会导致同步错误
``` javascript
let lrc = '[ti:白石溪][ar:洛天依/乐正绫][al:][by:][offset:0][00:00.10]白石溪 - 洛天依/乐正绫[00:00.20]词：果汁凉菜[00:00.30]曲：纯白[00:00.40]...'
lrc = lrc.replace(/\[/g, '\n[').trim()
```

用了一段时间，很喜欢 `APlayer` 简洁的UI，提一些其他可改进的建议：
1.我认为有必要提供动态管理播放列表的 `API`，如果没有，在需要动态添加歌曲到列表时只能重新 `new`
2.应该提供一个销毁播放器的 `API`
3.歌词允许异步添加，通常获取歌词接口是单独的（现在必须等待歌词接口返回再初始化播放器，若歌词获取失败或时间过长会同时影响到播放音乐功能）

**Comment by DIYgod** [comment]
Thanks for your suggestions.

The third point is realizable, see: http://aplayer.js.org/docs/#/?id=lrc-in-lrc-file-or-api

**Comment by Copay** [comment]
说实话某些歌词lrc的[]有重复，这是允许的。所以说这不是一蹴而就的事嘛

**Comment by vhyme** [comment]
lrc格式很多，一种是标准式，一行一个标签，一行一句歌词；还有压缩式，一行可能有多个标签；还有一种单行式（非标准），所有歌词都在一行里。后两种可能会在识别的时候出现冲突，因为如果都当成单行式的歌词，批量加换行符，会导致压缩式的无法正常工作（出现大量空行）；如果都当成压缩式，会导致空行变成下一行的歌词。**所以重点在于区分这两种歌词格式。**

我当时写安卓播放器的时候纯手撸了一个lrc parser，当时的解决办法是，如果歌词字符串总共只有一到两行，就认为是单行式，用正则批量加换行符；否则直接按照一般的歌词来处理。

实现起来也不难，可以考虑加上。

**Comment by Copay** [comment]
想法不错,想试试了

**Comment by liwanglin12** [comment]
我觉得还是用通行的换行式比较好。

**Comment by liwanglin12** [comment]
销毁那个在计划内了，很久之前提过

**Comment by metowolf** [comment]
@Copay 坐等 cPlayer 资瓷异步歌词

**Comment by DIYgod** [comment]
Done. a31d911948516ef5091753bae7051e5412e1d3f1
