### ISSUE TITLE
support mobile

### ISSUE THREAD

**Issue by cmideal** [MoePlayer/APlayer#125]
I think some user use aplayer for mobile first.

but find ,slider only work click ,cant slide

**Comment by remyabel** [comment]
If it doesn't work on mobile, it's probably due to ES6 features in the library. Look at http://caniuse.com/ to confirm. I ended up manually converting all of it to ES5 syntax, but a polyfill library like babel-js can work too.

**Comment by WyRe** [comment]
I'm having issues also with android browsers ... particularly the auto-play doesn't work.

**Comment by ericdrobinson** [comment]
>I'm having issues also with android browsers ... particularly the auto-play doesn't work.

Auto-play is hardcoded to _not_ work in mobile.

**Comment by DIYgod** [comment]
Done. 41478dc5f9a10b9787fdd1f84a6d786156260070
