### ISSUE TITLE
Make API function eleHTML

### ISSUE THREAD

**Issue by ghost** [MoePlayer/APlayer#127]
I use custom HTML/CSS for the APlayer which you can see here: https://github.com/remyabel/angels-of-clockwork/blob/master/js/APlayer.js#L56

Since I have not pulled in from upstream in a while, it's annoying to modify the src and build instead of just changing the HTML from the client-side. Would be nice if there was an API function for it. The reason why it's needed instead of just setting innerHTML directly is because it relies on APlayer variables (like this.option.theme, etc.)

**Comment by DIYgod** [comment]
I'll achieve this function.

**Comment by PTcampbell** [comment]
I agree with this. I think the structure of the markup is a bit too opinionated. You should be able to edit template without editing the JS file. Thanks for the plugin!

**Comment by DIYgod** [comment]
Template is now separated with js in [src/template](https://github.com/MoePlayer/APlayer/tree/master/src/template), you can modify easier.
