### ISSUE TITLE
Custom Error Message Option

### ISSUE THREAD

**Issue by iandersen** [MoePlayer/APlayer#128]
Would it be possible for you to implement the option to pass in a custom error message instead of the default "Error happens ╥﹏╥"? The tone doesn't fit too well with the project we are working on, and I think it would be better for our users if we could pass a more informative error message. Thank you!

**Comment by MPierre9** [comment]
@iandersen @DIYgod Is the custom error message feature still needed?

**Comment by iandersen** [comment]
It would still be very useful

**Comment by MPierre9** [comment]
Ok great! I'll work on a solution 👍

**Comment by DIYgod** [comment]
You can disable the default error handling like this:
```js
ap.events.events.error = null;
```
