### ISSUE TITLE
Inline source map breaks APlayer in IE10

### ISSUE THREAD

**Issue by micooz** [MoePlayer/APlayer#133]
- The steps to reproduce.

Open demo page in IE10.

- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.

Noop.

- Which versions of APlayer, and which browser / OS are affected by this issue?

v1.6.0, Windows 7/IE10

`Uglify` puts source map in distribution js, which contains unidentified `const` to IE10:

https://github.com/DIYgod/APlayer/blob/master/webpack.config.js#L15

Consider to remove this line to fix the problem for not-old-enough browsers.

**Comment by remyabel** [comment]
FYI this is a known UglifyJS issue: https://github.com/mishoo/UglifyJS2/issues/133

**Comment by DIYgod** [comment]
Done.
