### ISSUE TITLE
New buttons: next, previous and save playlist

### ISSUE THREAD

**Issue by martinweingart** [MoePlayer/APlayer#141]
Hi, the plugin is great but it will be perfect for me if it has some extra buttons. Two of those I think that are fundamental for playing music: next song and previous song. And an extra button for saving the playlist it will be awesome!

Thank you very much for your work!

**Comment by AnyListen** [comment]
+1

**Comment by MPierre9** [comment]
@martinweingart I agree. APlayer should have at least next and previous buttons especially when the player is in narrow mode otherwise the user has no easily accessible way of skipping the song. 

I managed to get simple "next song" and "previous song" buttons working when APlayer is in list mode

## Example 

### APlayer Currently
![aplayer-current](https://user-images.githubusercontent.com/27080760/34859033-cbc792c8-f721-11e7-9622-05b864f0b5f8.gif)

### APlayer With Next and Previous Buttons
![next song aplayer](https://user-images.githubusercontent.com/27080760/34859070-08ce85b4-f722-11e7-8238-758a98a1dd21.gif)

**Comment by k-dauda** [comment]
+1

**Comment by DIYgod** [comment]
I'm planning to make a fullscreen mode, next and previous buttons will be shown in that mode.

**Comment by WhiteFangWBC** [comment]
> @martinweingart I agree. APlayer should have at least next and previous buttons especially when the player is in narrow mode otherwise the user has no easily accessible way of skipping the song.
> 
> I managed to get simple "next song" and "previous song" buttons working when APlayer is in list mode
> 
> ## Example
> ### APlayer Currently
> ![aplayer-current](https://user-images.githubusercontent.com/27080760/34859033-cbc792c8-f721-11e7-9622-05b864f0b5f8.gif) [ ![aplayer-current](https://user-images.githubusercontent.com/27080760/34859033-cbc792c8-f721-11e7-9622-05b864f0b5f8.gif) ](https://user-images.githubusercontent.com/27080760/34859033-cbc792c8-f721-11e7-9622-05b864f0b5f8.gif) [ ](https://user-images.githubusercontent.com/27080760/34859033-cbc792c8-f721-11e7-9622-05b864f0b5f8.gif)
> 
> ### APlayer With Next and Previous Buttons
> ![next song aplayer](https://user-images.githubusercontent.com/27080760/34859070-08ce85b4-f722-11e7-8238-758a98a1dd21.gif) [ ![next song aplayer](https://user-images.githubusercontent.com/27080760/34859070-08ce85b4-f722-11e7-8238-758a98a1dd21.gif) ](https://user-images.githubusercontent.com/27080760/34859070-08ce85b4-f722-11e7-8238-758a98a1dd21.gif) [ ](https://user-images.githubusercontent.com/27080760/34859070-08ce85b4-f722-11e7-8238-758a98a1dd21.gif)

how u add that next and back button inside aplayer box ?

**Comment by WhiteFangWBC** [comment]
> ### APlayer With Next and Previous Buttons
> ![next song aplayer](https://user-images.githubusercontent.com/27080760/34859070-08ce85b4-f722-11e7-8238-758a98a1dd21.gif) [ ![next song aplayer](https://user-images.githubusercontent.com/27080760/34859070-08ce85b4-f722-11e7-8238-758a98a1dd21.gif) ](https://user-images.githubusercontent.com/27080760/34859070-08ce85b4-f722-11e7-8238-758a98a1dd21.gif) [ ](https://user-images.githubusercontent.com/27080760/34859070-08ce85b4-f722-11e7-8238-758a98a1dd21.gif)

how u add that next and back button inside the aplyer box ?
