### ISSUE TITLE
showing problem

### ISSUE THREAD

**Issue by yingshaoxo** [MoePlayer/APlayer#146]
if `author: ''`, it always show a `-`, that's annoying.

**Comment by MPierre9** [comment]
Hello, I have fixed this bug using a ternary operator in the following line of code:

`this.element.getElementsByClassName("aplayer-author")[0].innerHTML = this.music.author ? ' - ' + this.music.author : ''`

Will make a PR soon with the full fix. In the example below the first song "Preparation" has author: ''

![with and without author](https://user-images.githubusercontent.com/27080760/33187819-9a91fdc8-d062-11e7-96fe-ffd46aa5def1.JPG)

**Comment by DIYgod** [comment]
Fixed. Thank @MPierre9 .
