### ISSUE TITLE
Remove song from playlist ?

### ISSUE THREAD

**Issue by Sn0wBiT** [MoePlayer/APlayer#147]
Is there a function to allow us to remove song from playlist ?

**Comment by voz-fshare** [comment]
I need this function too

**Comment by qinst64** [comment]
+1

**Comment by MPierre9** [comment]
I got a fix in development 👍 

![delete-from-playlist](https://user-images.githubusercontent.com/27080760/33512277-ee3998c0-d6fa-11e7-8fb6-26f2bd4da1ef.gif)

Still needs some work but it's coming along :)

**Comment by qinst64** [comment]
thanks!  I would need an API to do it in javascript more.

**Comment by DIYgod** [comment]
@MPierre9 API is welcomed, but I don't think user need remove song on the interface.

**Comment by MPierre9** [comment]
@DIYgod  @qinst64, Oh ok I'll try to implement it as an API. Thanks for the feedback.

**Comment by MPierre9** [comment]
Got it to work as API! 

![aplayer-removesong](https://user-images.githubusercontent.com/27080760/33587744-77bd11fa-d93d-11e7-8402-1fa2822427dd.gif)

Will upload a Pull Request soon with the full code.

**Comment by MPierre9** [comment]
Should be closed?
