### ISSUE TITLE
APlayer should be added a counter switch

### ISSUE THREAD

**Issue by firedent** [MoePlayer/APlayer#150]
## COMPATIBILITY
Now, APlayer has its own counter when it plays a playlist.But some Hexo themes have their own counter too.so there will be two counter in `</ol>` like this
![](https://i.imgur.com/qq2yo4J.png)
![](https://i.imgur.com/1XEox4e.png)

## SUGGESTION
I think the counter in APlayer should be removed or APlayer should be added a counter switch which is off by default. In my views, the theme should add counter when user use `<ol>` but obviously, some themes didn't. Users could switch on the counter in APlayer when they find the theme doesn't implement it.

**Comment by DIYgod** [comment]
I think you should add some custom CSS styles.

**Comment by firedent** [comment]
Eh.......Maybe it's a little difficult for a back-end "engineer".Adding some custom CSS styles is not friendly for others too.
I think you can reject this idea. This issue is only a suggestion rather than a demand.

**Comment by DIYgod** [comment]
There are too many CSS styles and cases that I can not adapt them all.

Your custom CSS is easily to write:
```css
.article-entry ol li.aplayer-list-light:before {
    content: '';
}
```

**Comment by firedent** [comment]
@DIYgod The first picture I posted is wrong. There are no the other `<li>` tags. The `<li>` tag won't use `aplayer-list-light` unless being selected.
It's still a good suggestion.
![](https://i.imgur.com/j6dloam.png)
