### ISSUE TITLE
The `mutex` option doesn't work well in an "extreme" case

### ISSUE THREAD

**Issue by RexSkz** [MoePlayer/APlayer#151]
**It's just a discussion, because this case is such extreme that normal people won't encounter.**

Imagine we have two different module which dependes on APlayer (such as `vue-aplayer` or `my-aplayer-wrapper-vue` lol), it's possible that the two depended APlayer is from different folder, even from different version (for example `node_modules/vue-aplayer/node_modules/aplayer` and `node_modules/my-aplayer-wrapper-vue/node_modules/aplayer`).

To simplify the case, we just run `npm install aplayer --save`, then copy folder `aplayer` in folder `node_modules` twice, change their name to `aplayer2` and `aplayer3`.

Next we use this `App.vue`:

```vue
<template>
    <div id="app">
        <div id="player2" class="aplayer"></div>
        <div id="player3" class="aplayer"></div>
    </div>
</template>

<script>
import APlayer2 from 'aplayer2'
import APlayer3 from 'aplayer3'

export default {
    mounted() {
        // Since `APlayer2` and `APlayer3` are not the same, the `mutex` option is useless
        new APlayer2({
            element: document.getElementById('player2'),
            mutex: true,
            music: {
                title: '4年ぶりの里帰り',
                author: 'C-CLAYS',
                url: 'https://dn-rexskz.qbox.me/music/4%E5%B9%B4%E3%81%B6%E3%82%8A%E3%81%AE%E9%87%8C%E5%B8%B0%E3%82%8A.mp3',
                pic: 'http://pic.xiami.net/images/album/img92/77092/5342541358214393.jpg',
            }
        })
        new APlayer3({
            element: document.getElementById('player3'),
            mutex: true,
            music: {
                title: '秋姉妹のなく頃に',
                author: 'さーくるばんばんしー',
                url: 'https://dn-rexskz.qbox.me/music/%E7%A7%8B%E5%A7%89%E5%A6%B9%E3%81%AE%E3%81%AA%E3%81%8F%E9%A0%83%E3%81%AB.mp3',
                pic: 'http://p1.music.126.net/W9q4aOQt-PLKNonVY01l2A==/836728348780675.jpg',
            }
        })
    }
}
</script>
```

Here comes the page:

![Image](https://dn-coding-net-production-pp.qbox.me/1d5b4eea-4fca-48e8-929e-5471c2fc7553.png)

The reason why two APlayer play at the same time even if the `mutex` option is true, is that `APlayer2` and `APlayer3` are not the same. APlayer use the `instances` variable to maintain all players, but in this case, `instances` can't include all players.

Seems the only solution for this extreme case is to use global variable such as `window`, but I don't think is a good idea.

----

During my funny test, I found [`vue-aplayer`](https://github.com/MoePlayer/vue-aplayer) seems to have a bug. I wrote more than one `<a-player>` tag in a page, and when I toggle one player's playing state, other players act the same way. I'll make a new issue at `vue-aplayer` after a double check.

**Comment by DIYgod** [comment]
Yes, using global variable is not a good idea, so we can only operation the variable inside APlayer module.

This case is beyond APlayer module, if it happens, user should solve it himself by provided API.
