### ISSUE TITLE
The play() request was interrupted by a call to pause()

### ISSUE THREAD

**Issue by luojianet** [MoePlayer/APlayer#153]
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
(index):1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
(index):1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
(index):1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
link：http://www.xuliehaonet.com/index.php/music/
音乐顺序播放5-6首就开始报错了

**Comment by DIYgod** [comment]
It does not influence. Pretend you don't notice it.

**Comment by luojianet** [comment]
@DIYgod No longer playing

**Comment by baisheng** [comment]
Here is the code that solved :
`   
  /**
   * Play music
   */
  play (time) {
    if (Object.prototype.toString.call(time) === '[object Number]') {
      this.audio.currentTime = time
    }
    if (this.audio.paused) {
      const playPromise = this.audio.play()
      if (playPromise !== null) {
        playPromise.catch(() => { this.audio.play() })
      }
    }
  }
`

**Comment by luojianet** [comment]
@baisheng How to use your code?inject in my page,ok?

**Comment by xyuanmu** [comment]
最近也是被这个问题苦恼，特别是换歌，而歌曲没有载入的时候，直接所有的歌都播放不了了，找到this.isMobile&&this.audio?(this.audio.src=this.music.url,this.play())，把 this.isMobile&&删掉，看看能不能解决，不过这样一来流量会变大。

**Comment by luojianet** [comment]
I did nothing,this problem have done.
