### ISSUE TITLE
Can't autoplay when setting multiple autoplay for true

### ISSUE THREAD

**Issue by metowolf** [MoePlayer/APlayer#155]
## The steps to reproduce.
Modify https://github.com/MoePlayer/APlayer/blob/master/demo/demo.js#L42
```
autoplay: false,
```
to 
```
autoplay: true,
```

## Error information
```
Demo.html:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
Demo.html:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
```

## Screenshot
![2017-09-14 22 25 43](https://user-images.githubusercontent.com/2666735/30435184-c7a73b22-992e-11e7-94d3-8c9c46806f04.png)

**Comment by xyuanmu** [comment]
最近也是被这个问题苦恼，特别是换歌，而歌曲没有载入的时候，直接所有的歌都播放不了了，找到`this.isMobile&&this.audio?(this.audio.src=this.music.url,this.play())`，把 `this.isMobile&&`删掉，看看能不能解决，不过这样一来流量会变大。

**Comment by ericdrobinson** [comment]
We see this as well. You can read about the source of this issue at the shortlink in the console or simply [click here](https://developers.google.com/web/updates/2017/06/play-request-was-interrupted).

**Comment by DIYgod** [comment]
Done. e2e8884a45229b23233932f554f399bd2ea9d191 cf5972879a27459445aaf730f7777c9400667881 fb4211a0b050a065f1ecc3e5eb37b97f0bd96ffc
