### ISSUE TITLE
Design Aplayer like Zing Mp3 HTML5 Player?

### ISSUE THREAD

**Issue by tuannvbg** [MoePlayer/APlayer#156]
https://mp3.zing.vn/bai-hat/Noi-Thuong-Nhau-Thi-Dung-Lam-Trai-Tim-Em-Dau-Bich-Phuong/ZW80COFO.html
Aplayer design like Zing Mp3 Player with support .lrc style karaoke?

**Comment by DIYgod** [comment]
Feel free to make pull requests, thanks.
