### ISSUE TITLE
Can we have a loading circle over the current music picture when mp3 is loading?

### ISSUE THREAD

**Issue by magicknight** [MoePlayer/APlayer#160]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

#### 有时候网络问题，音乐文件加载比较慢，能不能在用户点击播放，而文件尚在加载的时候，给个菊花图表示正在加载？然后播放的时候再显示暂停图标。如果用户点播放没有任何反应，会造成困惑，谢谢！

If you want to report a bug, please provide the following information:

#### Can we have a loading circle over the current music picture, indicating that the mp3 is loading, after the click event on "play" button? Sometimes when the network is slow, this loading notice is useful.

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of APlayer, and which browser / OS are affected by this issue?

**Comment by DIYgod** [comment]
Done. 5e610b15e84a3fc032a8bf681f0ea9ebc591f939
