### ISSUE TITLE
Feature request: minimize/maximize button 

### ISSUE THREAD

**Issue by aerohub** [MoePlayer/APlayer#165]
Hello,
it would be nice to have a button in the button row and function for switching between wide and narrow modes.
Thanks

**Comment by MPierre9** [comment]
Hello, is it possible for me to work on this feature? Thanks

**Comment by DIYgod** [comment]
I think switching button is unnecessary.

**Comment by DIYgod** [comment]
Done. 1dc058c0c7d5f4353aeef3f50564d1bb84803d50
