### ISSUE TITLE
本地lrc不能显示吗QAQ

### ISSUE THREAD

**Issue by Abigail940404** [MoePlayer/APlayer#169]
本地歌词显示不了……

![image](https://user-images.githubusercontent.com/26321391/33642785-85b18bb2-da76-11e7-800c-055f708def21.png)

**Comment by DIYgod** [comment]
I can not help you without any error log or live demo.

**Comment by Abigail940404** [comment]
![image](https://user-images.githubusercontent.com/26321391/33647013-9ff2c042-da8d-11e7-9323-7024415ccb70.png)

This is the error log.I want to know how to use a local lrc because the code has:

![image](https://user-images.githubusercontent.com/26321391/33647055-e75de754-da8d-11e7-9e05-3c6cc27b2419.png)

**Comment by DIYgod** [comment]
I think error message is very clear: ERR_FILE_NOT_FONUND

**Comment by Abigail940404** [comment]
But this does already exist……
![image](https://user-images.githubusercontent.com/26321391/33655928-7bfd9ffa-daaf-11e7-9200-94b0e4c32c89.png)
And it cannot display it!
