### ISSUE TITLE
Playback Mode Option "Single" is Confusing

### ISSUE THREAD

**Issue by ericdrobinson** [MoePlayer/APlayer#172]
## Description

The `mode` option values are not well described in [the documentation](https://aplayer.js.org/docs/#/?id=options). When reading "single", there is nothing to indicate that this actually means "**loop** a single song". Confusingly, if you wish to play a single song without looping you must only load a single song and set the `mode` to "order" which feels like it is specific to a playlist.

###  Improve Documentation
This could be addressed in the documentation. Specifically, add something like:
```
// Optional, play mode, can be `random` (loop) `single` (loop) `circulation`(loop) `order`(no loop), default: `circulation`.
```

### Clean Up the Options
The `mode` is a combination of two standard options found in other players:

1) **Looping:** None, Repeat-1, Repeat-All
2) **Random:** List-Order, Random-Order

The "play mode" is a named combination of these. It would be more straightforward, however, to specify them separately. Further, it would allow you to cleanly tie the "Repeat" button to the Looping variable without modifying the ordering option.

**Comment by DIYgod** [comment]
Forgive for my poor English, in Chinese, we can express it only with one word, so I have great difficulty in expressing it well in English, it is very clear now according to your suggestions.

**Comment by ericdrobinson** [comment]
No worries! I fully understand the difficulty of working with a second language, especially one as difficult as English. **Thank you very much** for your efforts to maintain this project in English!

I only hope that my comments are helpful!

**Comment by DIYgod** [comment]
Done. 6029ce980c2bc3a5ba318d4bebaf334a2bba4463

I have separated `mode` to `loop` and `order`.
