### ISSUE TITLE
All demo sounds on the website return a 403

### ISSUE THREAD

**Issue by Haroenv** [MoePlayer/APlayer#182]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of APlayer, and which browser / OS are affected by this issue?

I can replicate this on any network on both my Mac and phone (from France)

**Comment by kn007** [comment]
Demo media only access for https://aplayer.js.org/

**Comment by Haroenv** [comment]
This happens on aplayer.js.org too (`Error happens ╥﹏╥`)  for all except the lyrics example

**Comment by kn007** [comment]
Hmm, sorry about that.
Which browser are you using? Any error in browser console?

Could you visit: http://pubstatic.upyun.com/cdn-stream-test.html to get CDN report?

**Comment by DIYgod** [comment]
Sorry, I made some frequency limit in CDN to save expensive traffic in China, please don't access it frequently.

**Comment by Haroenv** [comment]
Okay if this is on purpose, feel free to close the issue 👍
