### ISSUE TITLE
[HTML5 BUG] Sources needs to be reloaded

### ISSUE THREAD

**Issue by DragonZX** [MoePlayer/APlayer#185]
HTML5 players are using pause button to stop music. If it's internet radio stream, player pauses sound and playing it from time when it had been stopped and from cache. To keep it realtime we need to reload player anytime it's paused, but only if it's a stream.

**Comment by DIYgod** [comment]
You should do it by APlayer API.

**Comment by DragonZX** [comment]
Explain plz
