### ISSUE TITLE
How to set the default fold song list

### ISSUE THREAD

**Issue by yedajiang44** [MoePlayer/APlayer#190]
I want to make a playlist is deactivated state by default，how to do ?（我想让播放列表默认是收起状态）

**Comment by yedajiang44** [comment]
看源码后解决了，在js里上如下代码即可（resolved）
`
    //const ap1 = new APlayer({....})
    const list = document.getElementsByClassName('aplayer-list')[0];
    if (!list.classList.contains('aplayer-list-hide')) {
        list.classList.add('aplayer-list-hide');
    }
`

**Comment by yedajiang44** [comment]
感觉这样不是很优雅。。。希望作者指导下姿势。。。

**Comment by DIYgod** [comment]
Thanks, I'll make a new option to handle it.

**Comment by DIYgod** [comment]
Done. 021df59e850449cf06b60017be76772201f19cef

**Comment by yedajiang44** [comment]
@DIYgod nice！thanks for your work
