### ISSUE TITLE
Failed to parse SourceMap: http://www.ysblog.xyz/wp-content/plugins/Hermit-X-master/assets/js/APlayer.min.js.map 控制台报错（ﾉ´д｀）

### ISSUE THREAD

**Issue by 2391978156** [MoePlayer/APlayer#191]
中文用户请注意：请尽量用**英文**描述你的 issue，这样能够让尽可能多的人帮到你。

If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of APlayer, and which browser / OS are affected by this issue?

**Comment by kn007** [comment]
不存在文件，不会报错么？？

**Comment by 2391978156** [comment]
哦哦，我去看看

**Comment by kn007** [comment]
还有这个问题，去hermit-x提问。跑来APlayer提问我也是醉了。

看了下，因为hermit-x，没有引入这个文件，而js引入了sourcemap所致，不影响使用。
想要解除提示，你可以自己补充sourcemap或者跟lwl提议引入sourcemap或者对原js的sourcemap引入做删除。

**Comment by kn007** [comment]
cc @liwanglin12

**Comment by 2391978156** [comment]
好的，还不太会用github，大佬见笑了

**Comment by kn007** [comment]
没关系，我不是大佬。。

**Comment by liwanglin12** [comment]
我让他来ap的，这是ap的引用策略问题。

**Comment by kn007** [comment]
APlayer默认就是要引入sourcemap的啊。你使用却不留js.map。。

**Comment by DIYgod** [comment]
正常现象，不属于 bug，不予处理

**Comment by 2391978156** [comment]
大佬云集。。萌新瑟瑟发抖

**Comment by DIYgod** [comment]
APlayer has more than one hundred watchers, please don't reply pointless content.

This issue will be locked.
