### ISSUE TITLE
Reset CSS for Unified Display

### ISSUE THREAD

**Issue by a632079** [MoePlayer/APlayer#193]
Due to My English is not well , I give two languages below.
播放器目前会受上级样式干扰，造成在不同站点嵌入 （受上级 CSS 影响），会产生不同的显示效果。
例如：
* 字体不统一
* 边距不统一
* 字重不统一
基于这个，所以我曾经建立了  iframe 项目，为了统一的浏览器显示。 但其实这只是无奈的做法， 甚至某些时候还需要 js 来辅助适应元素 （Cplayer 的 播放列表）。 所以，很期待进行样式重置，以便统一的显示效果。

--------------------------------
Players will now be subject to superior style interference, resulting in embedded in different sites (by superior CSS effects), will have a different display.
E.g:
* Fonts are not uniform
* Margin/Padding is not uniform
* Font weight is not uniform
Based on this, so I have set up an iframe project, in order to display a unified browser. But in fact, this is just helplessness, and sometimes even need js to help adapt elements (such as: Cplayer's playlist). So, look forward to the style reset, in order to uniform display.

> Translated by Google.

**Comment by imlevis** [comment]
I encountered the same problem.

**Comment by wenguangcheng** [comment]
> Due to My English is not well , I give two languages below.
> 播放器目前会受上级样式干扰，造成在不同站点嵌入 （受上级 CSS 影响），会产生不同的显示效果。
> 例如：
> 
> * 字体不统一
> * 边距不统一
> * 字重不统一
>   基于这个，所以我曾经建立了  iframe 项目，为了统一的浏览器显示。 但其实这只是无奈的做法， 甚至某些时候还需要 js 来辅助适应元素 （Cplayer 的 播放列表）。 所以，很期待进行样式重置，以便统一的显示效果。
> 
> Players will now be subject to superior style interference, resulting in embedded in different sites (by superior CSS effects), will have a different display.
> E.g:
> 
> * Fonts are not uniform
> * Margin/Padding is not uniform
> * Font weight is not uniform
>   Based on this, so I have set up an iframe project, in order to display a unified browser. But in fact, this is just helplessness, and sometimes even need js to help adapt elements (such as: Cplayer's playlist). So, look forward to the style reset, in order to uniform display.
> 
> > Translated by Google.

你有遇到过数据请求回来之后，导致播放不了的问题吗？
