### ISSUE TITLE
播放状态能保存在session里吗？

### ISSUE THREAD

**Issue by sbmzhcn** [MoePlayer/APlayer#195]
每次打开新的页面，播放器就重置了，重新播放，无法记住上次的操作，可否加一个这样的功能，记住当前域名下，我之前的操作。

**Comment by DIYgod** [comment]
You can do it with APlayer API, such as `ap.audio.currentTime` `ap.seek(time)`.

**Comment by foreshadow** [comment]
new完直接seek好像没效果，on playing再seek也不行。。应该怎么用？
