### ISSUE TITLE
Hexo Yilia cannot use APlayer correctly

### ISSUE THREAD

**Issue by Azha3** [MoePlayer/APlayer#201]
I use hexo with Yilis as my theme, however I cannot load the player correct, the layoff of which is not load normally, and it have bad influence on the use of this player.

**Comment by SunjinPeng2017** [comment]
I use APlyer in yilia theme work well，you can consult it: http://www.sunjinpeng.cn/2018/06/21/hexo-bgm

**Comment by Azha666** [comment]
Thanks for your guidance.

**Comment by Azha666** [comment]
> I use APlyer in yilia theme work well，you can consult it: http://www.sunjinpeng.cn/2018/06/21/hexo-bgm

Thanks for your guidance.

**Comment by Azha666** [comment]
@SunjinPeng2017 Thanks for your guidance.
