### ISSUE TITLE
Version badge display error in Chrome 65

### ISSUE THREAD

**Issue by SevenOutman** [MoePlayer/APlayer#202]
Open https://aplayer.js.org in Chrome 65 and open Console
![2018-03-19 15-11-59](https://user-images.githubusercontent.com/8225666/37582479-29d2c262-2b88-11e8-8912-85ddda8c5361.png)

Seems a change in Chrome 65 rather than coding mistake.

**Comment by DIYgod** [comment]
Layout fixed (4af7cab5e75336dac3248503fbe6a5be891cfd13), but I have no idea about the link background.
![](https://i.imgur.com/E7D2KAB.png)

**Comment by SevenOutman** [comment]
@DIYgod Looks like Chrome detects links and set the background automatically. One solution is to remove `https://` from the link, that way Chrome won't treat it as hyperlink, but also it won't be clickable.
