### ISSUE TITLE
ap.list.remove() throw exception

### ISSUE THREAD

**Issue by gorden178** [MoePlayer/APlayer#205]
APlayer v1.10.0 5bfde99
APlayer.min.js?v=51.01:1 
Uncaught TypeError: Cannot read property 'parsed' of undefined
    at e.value (APlayer.min.js?v=51.01:1)
    at <anonymous>:1:24

**Comment by farwish** [comment]
#208  @gorden178

**Comment by DIYgod** [comment]
Fixed. https://github.com/MoePlayer/APlayer/commit/55039bbc3b91c592b3e711f7c34013f583185914
