### ISSUE TITLE
Any way to prevent lrc from auto loading in fixed-mode?

### ISSUE THREAD

**Issue by mashirozx** [MoePlayer/APlayer#215]
No need to show any  lyric since the music isn't on play. I've read the docs but seems no this option currently?

I mean this:
![image](https://user-images.githubusercontent.com/16148054/40277472-ff3d51fc-5c51-11e8-8845-d22bd9cfe676.png)

**Comment by DIYgod** [comment]
You can hide/show it in pause/play event

**Comment by mashirozx** [comment]
Thanks.
