### ISSUE TITLE
Progress bar and  volume bar can't work when it's parent element applying transform style

### ISSUE THREAD

**Issue by bulatie** [MoePlayer/APlayer#216]
I found source code using *getElementViewLeft* to get its position relative to the viewport, but this function can't work with transform style.

Here is my bug demo.
[demo](https://codesandbox.io/s/kmj7olo0qo)

I suggest using *getBoundingClientRect* to get its position relative to the viewport.

**Comment by DIYgod** [comment]
Fixed. 94df89539491e2b6846b191b7154276cfdcec1e9
