### ISSUE TITLE
a bug of unicode hash in smoothscroll

### ISSUE THREAD

**Issue by wangriyu** [MoePlayer/APlayer#217]
- The steps to reproduce.

use Chinese characters for id and anchor in html，then click `<a href="#中文字符"/>` would be unresponsive

- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.

preview in [codepen](https://codepen.io/wangriyu/full/aGraGO)，click Chinese anchor would be unresponsive

- Which versions of APlayer, and which browser / OS are affected by this issue?

Aplayer 1.10.1 - smoothscroll 0.4.0
Mac OS 10.13.4
Chrome 66.0.3359.181

- Solution

https://github.com/alicelieutier/smoothScroll/pull/49

**Comment by DIYgod** [comment]
Wait for smoothScroll to fix it.

**Comment by TsingSu** [comment]
> 等待smoothScroll修复它。

这个BUG是否已经修复
