### ISSUE TITLE
Multi-language lyrics display problem

### ISSUE THREAD

**Issue by paultw** [MoePlayer/APlayer#222]
I've got a kind of .lrc file which contains multi-languages.   

The format as follows：
....
[00:29.046] 中文歌詞第一行
[00:29.046] english lyrics line 1
[00:34.187] 中文歌詞第二行
[00:34.187] english lyrics line 2
.......

The aplayer can only show one current lyric line (usually the last one), 
which means the upper lyrics (with same time tag ) will be cut off.

Could it be possible that  aplayer to show multi-language at the same time?

Thank you.

**Comment by DIYgod** [comment]
Repeat with #219
