### ISSUE TITLE
APlayer can't work on the WebView component of Android

### ISSUE THREAD

**Issue by Dkevin2018mc** [MoePlayer/APlayer#226]
APlayer can't work on the WebView component of Android, but it is normal in other browsers. There will be a lower picture.I use the Lua language to create this application (Androlua)
![screenshot_2018-06-16-00-08-06-891_com kirin project kango](https://user-images.githubusercontent.com/26665166/41478187-5b1b0710-70f9-11e8-8399-2191d6f47b66.png)

**Comment by SevenOutman** [comment]
@Dkevin2018mc Are you getting any error messages in your console (or wherever the output goes).

**Comment by Dkevin2018mc** [comment]
@SevenOutman Nothing.

**Comment by Dkevin2018mc** [comment]
settings = player.getSettings();
settings.setJavaScriptEnabled(true);
settings.setDomStorageEnabled(true);
I solved it!(≧∇≦)
