### ISSUE TITLE
Can't use process bar when using stream audio

### ISSUE THREAD

**Issue by yuri147** [MoePlayer/APlayer#230]
This nice player maybe should support with stream buffer?

**Comment by DIYgod** [comment]
what kind of stream audio

**Comment by yuri147** [comment]
like
`
fs.createReadStream(filePath).pipe(res);
`
the process bar doesn't work

**Comment by DIYgod** [comment]
I can't understand, how do you use `fs` in broswer?

**Comment by yuri147** [comment]
It's been solved on server side.never mind,thanks
