### ISSUE TITLE
how to remove Browser address bar rightmost character "/#/"

### ISSUE THREAD

**Issue by iloveleeyan** [MoePlayer/APlayer#249]
i use APlayer, but is has a small problem, that is affecting the normal usage :

when we use browser to visit a web page that using APlayer, it will automatically adding a hash  character "/#/" at the rightmost of the browser address bar ！

> https://aplayer.js.org/#/

how to remove it？ who knows to alter the source code？

[aplayer_char.png](http://lablee.cn/aplayer_char.png)

**Comment by DIYgod** [comment]
It's caused by other script in the page, not APlayer.

**Comment by iloveleeyan** [comment]
> 
> 
> It's caused by other script in the page, not APlayer.

thanks for reply

can you tell me how to remove it? 
i refer to the code  https://aplayer.js.org/#/, and alter it 
i try to delete some useless code, but mo effect ,or the player just disappeared ...
