### ISSUE TITLE
无法解析只精确到秒的歌词

### ISSUE THREAD

**Issue by inkedawn** [MoePlayer/APlayer#39]
```
[00:59]上路 巩州遇虎熊 （熊山君，寅将军）
[01:01]五百年前一场疯 腾宵又是孙悟空 （孙悟空）
[01:05]失马 鹰愁涧飞白龙 （白龙马）
[01:07]沙河阻断路难通 福陵山中收天蓬 （沙和尚，猪八戒）
[01:11]岭上 前行逆黄风 （黄风怪）
[01:14]七星不照波月洞 千年白骨化阴风 （奎木狼，白骨精）
[01:18]鱼篮 网通天一尾红 （灵感大王）
[01:20]紫金葫芦二道童 九尾老狐敢压龙 （金、银角大王，压龙大仙）
[01:24]白虹坠 雪浪击石碎
[01:27]思归 难归 堕回 轮回
```

**Comment by DIYgod** [comment]
一般不会出现这种格式的吧，这段歌词是哪里找的？

**Comment by aprikyblue** [comment]
黄易云音乐获取的，不显示歌词，然后调试发现是这首的歌词没毫秒的原因。。。
其实也有不少啊，只不过这几年比较少见了
[mm:ss.xx] [mm:ss] [mm:ss:xx] 一般就这三种格式。。

**Comment by 951452292** [comment]
?

**Comment by liwanglin12** [comment]
这首歌ID能给我看看么？

**Comment by rainfroid** [comment]
@liwanglin12 就是九九八十一啊 id=404543406

**Comment by liwanglin12** [comment]
略尴尬。。。
Hermit-X 也不支持这种歌词

rainfroid <notifications@github.com>于2016年9月18日周日 下午11:24写道：

**Comment by DIYgod** [comment]
@liwanglin12 这种歌词多么？

**Comment by liwanglin12** [comment]
不知道啊(o_ _)ﾉ我试了一下他上面给的ID，raw输出是可以的但是到最后重复输出了一点东西。。挺奇怪的，国庆节看看

Wenjie Fan <notifications@github.com>于2016年9月19日周一 上午9:43写道：

**Comment by freejishu** [comment]
http://music.163.com/#/song?id=38592976
Dream It Possible - Delacey
网易云返回的也是这种歌词

> [00:08]I will run, I will climb, I will soar
[00:13]I’m undefeated
[00:16]Jumping out of my skin, pull the chord

**Comment by Copay** [comment]
@freejishu aplayer的歌词解析模块对数字判断的问题么

**Comment by liwanglin12** [comment]
@freejishu 拿Meting解析歌词，自动避过这个问题（逃

**Comment by freejishu** [comment]
@liwanglin12 就是通过Meting解析的歌词
@Copay 因为看到是new APlayer这一行报错 又看了一下歌词这样 就来找这篇帖子了。。错误信息我没太细看，也忘了留下了。。

**Comment by wjm2038** [comment]
@freejishu 那先去再试一下看看能不能留个日志啊

**Comment by freejishu** [comment]
Uncaught TypeError: Cannot read property 'addMusic' of undefined
    at Object.success (core.js:74)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at A (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)

**Comment by metowolf** [comment]
@liwanglin12 事实上那个歌词解析模块并没有集成在 Meting 里，我分别在 HermitX 和 Aplayer-Typecho 两个插件中内置了

**Comment by DIYgod** [comment]
Done. 7b9074ffd03b65f02c14e6ab0431ab5d72768a71
