### ISSUE TITLE
Add support for Enhanced formated LRC

### ISSUE THREAD

**Issue by danvim** [MoePlayer/APlayer#52]
https://en.wikipedia.org/wiki/LRC_(file_format)#Enhanced_format

Using enhanced LRC format, lyrics can sync song lines word by word. This could be a nice update for the player.

**Comment by Copay** [comment]
Is it like a MV's Lyric?

**Comment by danvim** [comment]
@Copay By "MV", do you mean those MTVs/Karaokes?

But as I imagine. All the separated lyrics in a line are wrapped in `<span>`s. They are all gray at first and then they fade into a color or wipe into a color by adding classes.

Here is a gradient code pen I found that works on Firefox (It doesn't have to be included though, just an idea): https://codepen.io/giana/pen/RPdLaQ I imagine you can do a gradient and translate the background position to do the wiping animation. Of course simply fading would be simpler if you want to though.

That shouldn't be too hard to add to the code, right? :laughing:

**Comment by Copay** [comment]
but the author is a little lazy?he is buzy with DPlayer, his new project.

**Comment by DIYgod** [comment]
Done. 44ff1c8ff7d7faf233a3e195b58b95064e1bc034
